### ISSUE TITLE
Seems to have stopped working on X/Twitter

### ISSUE THREAD

**Issue by Shiranui-Izayoi** [solorey/Art-Saver#55]
Over the last day or 2 I haven't been able to make it work on X/Twitter. When I hit the download button it will fail with a red exclamation point saying "TypeError: NetworkError when attempting to fetch resource." 

I think they may have changed something in the backend or similar. When I check the console the full error is as follows.
```
[Art Saver] TypeError: NetworkError when attempting to fetch resource. [main.js:115:17](moz-extension://0be2a8bf-9f7a-46f0-81e5-ee11e4617bef/content/scripts/main.js)
    asLog moz-extension://0be2a8bf-9f7a-46f0-81e5-ee11e4617bef/content/scripts/main.js:115
    downloadNext moz-extension://0be2a8bf-9f7a-46f0-81e5-ee11e4617bef/content/scripts/classes.js:578
```
Hope this helps fix whatever the issue is. And also that this is not an error only effecting me.

**Comment by solorey** [comment]
I can confirm this issue. It seems whenever this extension tries to download an image from X, Firefox now classifies the network request as a 'SocialTracker' and blocks it when tracking protection is on. For now turning off blocking Tracking content should make this extension work again for X.

**Comment by solorey** [comment]
This has been fixed in v2.3.2

**Comment by VGDCM** [comment]
I'm still getting it in v2.3.3, but only on my Windows 7 computer. Windows 10 works fine
